name: core_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.6.0
  xxtea: ^2.1.0
  crypto: ^3.0.3
  validators: ^3.0.0
  dio: ^5.4.2+1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  intl_phone_field: ^3.2.0
  telephony: ^0.2.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^7.0.1
  url_launcher: ^6.3.0
  app_links: ^6.2.0
  cached_network_image: ^3.3.1
  flash: ^3.1.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  path_provider: ^2.1.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/application/login/
    - assets/images/widget_images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
